# Generated by Django 2.2.4 on 2020-09-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FileType', models.CharField(choices=[('File_R MCP_Quarterly_Enrollment_File', 'File_R MCP_Quarterly_Enrollment_File'), ('File_R Revised MCP_Quarterly_Enrollment_File for Add/Del', 'File_R Revised MCP_Quarterly_Enrollment_File for Add/Del'), ('File_D  MCP_payment_and_attribution_validation File for CPC', 'File_D  MCP_payment_and_attribution_validation File for CPC'), ('File_J  CPC Practice Summary Report/ CPC Partnership Summary Report File', 'File_J  CPC Practice Summary Report/ CPC Partnership Summary Report File'), ('File_O CPC Member-level provider report CSV data file for MCPs', 'File_O CPC Member-level provider report CSV data file for MCPs'), ('File_G5 CPC Shared savings payment file for MCPs', 'File_G5 CPC Shared savings payment file for MCPs')], default='none', max_length=256, verbose_name='File Type')),
                ('ManagedCarePlan', models.CharField(choices=[('BUCKEYE', 'BUCKEYE'), ('CARESOURCE', 'CARESOURCE'), ('MOLINA', 'MOLINA'), ('PARAMOUNT', 'PARAMOUNT'), ('UNITED', 'UNITED')], default='none', max_length=256, verbose_name='Managed Care Plan')),
                ('PerformanceYear', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='none', max_length=256, verbose_name='Performance Year')),
                ('QuarterOrAnnualIdentifier', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Annual', 'Annual')], default='none', max_length=256, verbose_name='Quarter or Annual Identifier')),
                ('KnownData', models.TextField(max_length=2000, verbose_name='Known Data Quality Issues')),
                ('ChangestotheFileinthisDelivery', models.TextField(max_length=2000, verbose_name='Changes to the File in this Delivery')),
                ('UpcomingChanges', models.TextField(max_length=2000, verbose_name='Upcoming Changes approved by ODM and Tentative Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'ReadMe data',
                'verbose_name_plural': 'ReadMe',
                'db_table': 'tbl_readme_file',
                'ordering': ('created_at',),
            },
        ),
    ]
