# Generated by Django 3.0.5 on 2020-04-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileType', models.CharField(max_length=256, verbose_name='File Type')),
                ('PerformanceYear', models.CharField(max_length=256, verbose_name='Performance year(s)')),
                ('QuarterOrAnualIswntifier', models.CharField(max_length=256, verbose_name='Quarter or Annual Identifier(s)')),
                ('KnownData', models.CharField(max_length=256, verbose_name='Known data quality issues')),
                ('expectedFieldChanges', models.CharField(max_length=256, verbose_name='Expected Field changes')),
                ('UpcomingChanges', models.CharField(max_length=256, verbose_name='Upcoming changes approved by ODM')),
                ('UserName', models.CharField(max_length=256, verbose_name='User Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'ReadMe data',
                'verbose_name_plural': 'ReadMe',
                'db_table': 'tbl_readme_file',
                'ordering': ('created_at',),
            },
        ),
    ]
