# Generated by Django 2.2.5 on 2020-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readmemodel',
            name='PerformanceYear',
        ),
        migrations.RemoveField(
            model_name='readmemodel',
            name='expectedFieldChanges',
        ),
        migrations.AddField(
            model_name='readmultiplefile',
            name='KnownData',
            field=models.TextField(choices=[('a', 'Know1'), ('b', 'Know2')], default=1, max_length=256, verbose_name='Known data quality issues'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readmultiplefile',
            name='expectedFieldChanges',
            field=models.TextField(max_length=256, verbose_name='Expected Field changes'),
        ),
    ]
