# Generated by Django 2.2.4 on 2020-09-16 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmemodel',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='readmemodel',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='readmemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
