# Generated by Django 3.0.5 on 2020-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme_service', '0002_remove_readmemodel_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmemodel',
            name='FileType',
            field=models.CharField(default=1, max_length=256, verbose_name='File Type'),
            preserve_default=False,
        ),
    ]
