# Generated by Django 3.0.5 on 2020-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme_service', '0003_readmemodel_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='readmemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
